Resources:
  MySecG:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Allow http and ssh ingress and engress on any port ans protocol.
      SecurityGroupIngress:
      - IpProtocol: 'tcp'
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: 'tcp'
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0