version: 2.1

executors:
  my-executor:
    docker:
      - image:  alpine:latest

jobs:
  smoke-test:
    executor: my-executor
    steps:
      - run:
          name: Updating Alpine Packages
          command:  |
            apk update
      - run:
          name: Upgrading Alpine Packages
          command:  |
            apk upgrade
      - run:
          name: Installing curl
          command:  |
            apk add curl
      - run:
          name: Checking curl verison
          command:  |
            curl --version
      - run:
          name: Running Test
          command:  |
            if curl -s --head "https://googleisasnitch.com"
            then
              echo "It worked!"
            else
              echo "It failed..."
              exit(1)
            fi


workflows:
  Testing:
    jobs:
      - smoke-test