version: 2.1

executors:
  aws-cli:
    docker:
      - image:  amazon/aws-cli

jobs:
  test-checkout:
    executor: aws-cli
    steps:
      - checkout
      - run:
          command:  |
            ls -a
            yum install -y util-linux
            sudo yum install epel-release
            sudo yum install snapdsudo systemctl enable --now snapd.socket
            sudo ln -s /var/lib/snapd/snap /snap
            sudo snap install tree
            tree .

workflows:
  commit:
    jobs:
      - test-checkout