version: 2.1

executors:
  alpine:
    docker:
      - image:  python:3.7-alpine3.11
jobs:
  play-ansible:
    executor: alpine
    working_directory: ~/ci-cd
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: 
            - 9d:4d:98:76:bf:2e:6e:99:1f:9d:2d:ae:b3:1d:51:16
      - run:
          name: Installing Ansible
          command:  |
            apk add ansible
      - run:
          name: Adding ansible.cfg file
          command:  |
            echo "[defaults]" | cat > ansible.cfg
            echo "host_key_checking = False" | cat >> ansible.cfg
      - run:
          name: Play
          command:  |
            yes | ansible-playbook main.yml -i inventory
          no_output_timeout: 3m

            

workflows:
  playing:
    jobs:
      - play-ansible