version: 2.1

executors:
  aws-cli:
    docker:
      - image:  amazon/aws-cli

jobs:
  smoke-test:
    executor: aws-cli
    steps:
      - checkout
      - run:
          name: Create a stack
          command:  |
            aws cloudformation create-stack --stack-name demo-stack --template-body file://template.yml
      - run:
          name: Failed Test
          command:  |
            exit 1
      - run:
          name: Rolling Back
          command:  |
            aws cloudformation delete-stack --stack-name demo-stack
          when: on_fail

workflows:
  rollback-test:
    jobs:
      - smoke-test