version: 2.1

executors:
  aws-cli:
    docker:
      - image:  amazon/aws-cli

jobs:
  test-checkout:
    executor: aws-cli
    steps:
      - checkout
      - run:
          command:  |
            ls -a
            yum update && yum install -y sudo
            yum update && sudo yum install -y snapd
            ssystemctl enable --now snapd.socket
            ln -s /var/lib/snapd/snap /snap
            exec bash
            sudo snap install tree
            tree .

workflows:
  commit:
    jobs:
      - test-checkout