version: 2.1

executors:
  alpine:
    docker:
      - image:  python:3.7-alpine3.11
jobs:
  play-ansible:
    executor: alpine
    working_directory: ~/ci-cd
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: 
            - 9d:4d:98:76:bf:2e:6e:99:1f:9d:2d:ae:b3:1d:51:16
      - run:
          name: Installing-Dependencies
          command:  |
            apt-get update -y
            apt-get install sudo -y
            apt-get update -y
      - run:
          name: Installing-Ansible
          command:  |
            sudo apt-add-repository ppa:ansible/ansible
            sudo apt-get update -y
            sudo apt install ansible -y
      - run:
          name: Play
          command:  |
            ansible-playbook main.yml -i inventory
          no_output_timeout: 5m

            

workflows:
  playing:
    jobs:
      - play-ansible