version: 2.1

executors:
  my-executor:
    docker:
      - image:  circleci/node:13.8.0

jobs:
  
  save_output:
    executor: my-executor
    steps:
      - run:
          command:  |
            echo "Hello World" > output.txt
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - output.txt

  print_output:
    executor: my-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: |
            cat output.txt

workflows:
  commit:
    jobs:
      - save_output
      - print_output:
          requires:
            - save_output