version: 2.1

executors:
  aws-cli:
    docker:
      - image:  amazon/aws-cli

jobs:
  test-checkout:
    executor: aws-cli
    working_directory: ~/source-code
    steps:
      - checkout
      - run:
          command:  |
            pwd
            ls -a
            yum update -y && yum install sudo -y
            sudo yum install git -y
            git branch -a

workflows:
  tests:
    jobs:
      - test-checkout