version: 2.1

commands:
  print_pipeline_id:
    description:  "Commands to print the pipeline id."
    steps:
      - run:
          echo << pipeline.id >>
executors:
  my-executor:
    docker:
      - image:  circleci/node:13.8.0

jobs:
  simple-command:
    executor: my-executor
    steps:
      - print_pipeline_id

workflows:
  commit:
    jobs:
      - simple-command