version: 2.1

executors:
  my-executor:
    docker:
      - image:  circleci/node:13.8.0

jobs:
  fail_test:
    executor: my-executor
    steps:
      - run:
          command:  |
            return 1
      - run:
          name: Failed State
          command: echo "Hello Error!"
          when: on_fail

workflows:
  commit:
    jobs:
      - fail_test