version: 2.1

executors:
  my-executor:
    docker:
      - image:  circleci/node:13.8.0

jobs:
  
  save_output:
    executor: my-executor
    steps:
      - run:
          command:  |
            mkdir tmp
            mkdir /tmp/workspace
            echo "Hello World" > output.txt
            mv output.txt /tmp/workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - output.txt

  print_output:
    executor: my-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          command: |
            ls

workflows:
  Sharing_Files:
    jobs:
      - save_output
      - print_output:
          requires:
            - save_output`