version: 2.1

executors:
  aws-cli:
    docker:
      - image:  amazon/aws-cli

jobs:
  create_infrastructure:
    executor: aws-cli
    steps:
      - run:
          command:  |
            aws s3 ls
            cat ~/.aws/credentials

workflows:
  creating-infra:
    jobs:
      - create_infrastructure