version: 2.1

executors:
  node:
    docker:
      - image:  circleci/node:13.8.0

jobs:
  print-workflow-id:
    executor: node
    steps:
      - run:
          command:  |
            echo "$CIRCLE_WORKFLOW_ID"

workflows:
  main-commit:
    jobs:
      - print-workflow-id