version: 2.1

executors:
  aws-cli:
    docker:
      - image:  amazon/aws-cli

jobs:
  create_infrastructure:
    executor: aws-cli
    steps:
      - run:
          command:  |
            cat /etc/os-release
            sudo yum update -y
            sudo yum install git -y
            git version
            git clone https://github.com/akshtrikha/hello-CircleCI
            cd hello-CircleCI/
            git checkout circleci-project-infrastructure-creation
            cp scripts/template.yml ./
            aws cloudformation create-stack --stack-name ansible-demo --template-body file://template.yml
            echo "Done!"
            

workflows:
  creating-infra:
    jobs:
      - create_infrastructure