version: 2.1

executors:
  my-executor:
    docker:
      - image:  circleci/node:13.8.0

jobs:
  print_name:
    executor: my-executor
    steps:
      - run:
          command:  |
            echo "My name is: $MY_NAME"

workflows:
  commit:
    jobs:
      - print_name